# Generated by Django 4.1.1 on 2022-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_s_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, choices=[('JOB', 'JOB'), ('COMMENT', 'COMMENT'), ('STORY', 'STORY'), ('POLL', 'POLL'), ('POLLOPT', 'POLLOPT')], max_length=7, null=True),
        ),
    ]
