# Generated by Django 4.1.1 on 2022-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_text_alter_news_title_alter_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
