# Generated by Django 4.1.1 on 2022-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_synced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='news',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
